name: pscis_env
channels:
  - esri
  - anaconda
  - defaults
dependencies:
  - python=3.11
  - arcgis
  - python-dotenv
  - pip
  - pip:
    - "--editable=git+https://github.com/bcgov/Integrated_Solutions.git#egg=configuration_and_functions&subdirectory=PSCIS/survey_to_esf/configuration_and_functions"